/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.RecetaDB;
import Modelo.Consulta;
import Modelo.Mascota;
import Modelo.Receta;
import Modelo.Servicio;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class frmListaRecetas extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form frmListaRecetas
     */
    RecetaDB recetaBD = new RecetaDB();

    public frmListaRecetas() {
        initComponents();  
        iniciar();

    }

    private void iniciar() {
        tablaModel();
        llenarTablaListaReceta("A");
    }

    private void llenarTablaListaReceta(String estado) {
        tablaModel();
        List<Receta> listaRec = null;
//        List<Mascota> listaM = null;
        listaRec = recetaBD.cargaRecetaTabla(estado, listaRec);
         SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");


        for (Receta lista : listaRec) {
            model.addRow(new Object[]{
                lista.getId_receta(), lista.getNum_receta(),
                formatofecha.format(lista.getFecha_receta()),
             
                
                lista.getConsulta().getMascota().getPersona().getCedula(),
                lista.getConsulta().getMascota().getPersona().getNombre()+", "+lista.getConsulta().getMascota().getPersona().getApellido(),
                lista.getConsulta().getMascota().getNombre()
 
            });
        }
    }

    private String retornaFechaString(Calendar fecha, int dias) {
        String retorno = null;
        fecha.add(Calendar.DAY_OF_YEAR, dias);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (fecha != null) {
            retorno = sdf.format(fecha.getTime());
        }
        return retorno;
    }

    private void tablaModel() {
        // metodo sirve para llamar a los campos que se hayan guardado en la base de datos
//              tablaServicios.getColumnModel().getColumn(0).setMaxWidth(0);
//        tablaServicios.getColumnModel().getColumn(0).setMinWidth(0);
//        tablaServicios.getColumnModel().getColumn(0).setPreferredWidth(0);

        tablaListaRecetas.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaListaRecetas.getColumnModel().getColumn(0).setMinWidth(0);
        tablaListaRecetas.getColumnModel().getColumn(0).setPreferredWidth(0);

        tablaListaRecetas.getColumnModel().getColumn(1).setMaxWidth(350);
        tablaListaRecetas.getColumnModel().getColumn(2).setMaxWidth(300);
        tablaListaRecetas.getColumnModel().getColumn(3).setMaxWidth(350);
        tablaListaRecetas.getColumnModel().getColumn(4).setMaxWidth(300);
        tablaListaRecetas.getColumnModel().getColumn(5).setMaxWidth(300);
        model = (DefaultTableModel) tablaListaRecetas.getModel();
        model.setNumRows(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarCi = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaRecetas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarCi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarCi.setText("Buscar por Nro");
        btnBuscarCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCiActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, 30));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 310, 30));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        jLabel1.setText("LISTA DE RECETAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        tablaListaRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NUMERO", "FECHA", "CÉDULA", "CLIENTE", "MASCOTA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListaRecetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListaRecetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListaRecetas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 830, 280));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOP1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaListaRecetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListaRecetasMouseClicked
          
    }//GEN-LAST:event_tablaListaRecetasMouseClicked

    private void btnBuscarCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCiActionPerformed
     if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LLENAR CAMPO REQUERIDO", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
         buscaReceta(txtBuscar.getText());
//            chkDesactivados.setSelected(false);
        }
    }//GEN-LAST:event_btnBuscarCiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListaRecetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaListaRecetas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
    private void buscaReceta(String num) {
        model.setNumRows(0);
   SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/yyyy");
        List<Receta> lis = null;
        lis = recetaBD.buscarReceta(num, lis);

        if (lis.size() > 0) {
            for (Receta lista : lis) {
                model.addRow(new Object[]{
                    lista.getId_receta(), lista.getNum_receta(),
                formatofecha.format(lista.getFecha_receta()),           
                lista.getConsulta().getMascota().getPersona().getCedula(),
                lista.getConsulta().getMascota().getPersona().getNombre()+", "+lista.getConsulta().getMascota().getPersona().getApellido(),
                lista.getConsulta().getMascota().getNombre()
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "SERVICIO NO ENCONTRADO", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            txtBuscar.requestFocus();
            llenarTablaListaReceta("A");
        }
    }
}
