/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import Controlador.controladorConsulta;
//import Controlador.MascotaDB;
//import Modelo.Consulta;
//import Modelo.Mascota;
import Controlador.ConsultaDB;
import Controlador.PersonaDB;
import Controlador.RecetaDB;
import Controlador.Validaciones;
import Modelo.Consulta;
import Modelo.Mascota;
import Modelo.Persona;
//import static Vista.frmConsulta.cc;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Personal
 */
public class frmListaConsulta extends javax.swing.JDialog {

    DefaultTableModel model;
    Validaciones validar = new Validaciones();
    ConsultaDB conDB = new ConsultaDB();
    PersonaDB perDB = new PersonaDB();
    DefaultTableModel modelConsulta;

    /**
     * Creates new form frmListaConsulta
     */
    public frmListaConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();
    }

    private void iniciar() {
        jTextAreaMotivo.setEditable(false);
        jTextAreaDiagnostico.setEditable(false);
        jTextFieldBuscar.setToolTipText("Ingrese el nombre o la cedula del dueño de la mascota. ");
        llenarTabla();
    }

    private void llenarTabla() {
        tableModel();
        List<Consulta> lista = null;
        lista = conDB.cargarConsulta(lista);
        for (Consulta consulta : lista) {
            model.addRow(new Object[]{consulta.getId(), consulta.getMascota().getNombre(),
                consulta.getPresion(), consulta.getTemp(), consulta.getPeso(), consulta.getMascota().getPersona().getCedula(),
                consulta.getMascota().getPersona().getNombre() + " " + consulta.getMascota().getPersona().getApellido(),
                consulta.getVeterinario(), consulta.getFecha()});
        }
    }

    private void tableModel() {

        TableConsultas.getColumnModel().getColumn(0).setMaxWidth(0);
        TableConsultas.getColumnModel().getColumn(0).setMinWidth(0);
        TableConsultas.getColumnModel().getColumn(0).setPreferredWidth(0);

        TableConsultas.getColumnModel().getColumn(1).setPreferredWidth(300);
        TableConsultas.getColumnModel().getColumn(2).setPreferredWidth(300);
        TableConsultas.getColumnModel().getColumn(3).setPreferredWidth(300);
        TableConsultas.getColumnModel().getColumn(4).setPreferredWidth(300);
        TableConsultas.getColumnModel().getColumn(5).setPreferredWidth(300);
        TableConsultas.getColumnModel().getColumn(6).setPreferredWidth(300);
        TableConsultas.getColumnModel().getColumn(7).setPreferredWidth(300);
        TableConsultas.getColumnModel().getColumn(8).setPreferredWidth(300);

        model = (DefaultTableModel) TableConsultas.getModel();
        model.setNumRows(0);
    }

    private void buscarConsulta(String busqueda) {
        model.setNumRows(0);
        List<Consulta> busca = new ArrayList<>();
        List<Consulta> lista = null;
        lista = conDB.cargarConsulta(lista);
        for (int i = 0; i < lista.size(); i++) {
            String nom = lista.get(i).getMascota().getPersona().getNombre() + " " + lista.get(i).getMascota().getPersona().getApellido();
            if (lista.get(i).getMascota().getPersona().getCedula().equals(busqueda)) {
                busca.add(lista.get(i));
            } else if (lista.get(i).getMascota().getPersona().getNombre().equalsIgnoreCase(busqueda)
                    || lista.get(i).getMascota().getPersona().getApellido().equalsIgnoreCase(busqueda)) {
                busca.add(lista.get(i));
            } else if (nom.equalsIgnoreCase(busqueda)) {
                busca.add(lista.get(i));
            }
        }

        if (busca.size() > 0) {
            for (Consulta cons : busca) {
                model.addRow(new Object[]{cons.getId(), cons.getMascota().getNombre(),
                    cons.getPresion(), cons.getTemp(), cons.getPeso(), cons.getMascota().getPersona().getCedula(),
                    cons.getMascota().getPersona().getNombre() + " " + cons.getMascota().getPersona().getApellido(),
                    cons.getVeterinario(), cons.getFecha()});
            }

        } else {
            JOptionPane.showMessageDialog(null, "CLIENTE NO ENCONTRADO", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            llenarTabla();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableConsultas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonbuscarConsulta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMotivo = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDiagnostico = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MASCOTA", "PRESIÓN", "TEMPERATURA", "PESO", "CÉDULA", "DUEÑO", "VETERINARIO", "FECHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableConsultas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 1060, 220));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel1.setText("LISTA DE CONSULTAS ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 310, 30));

        jButtonbuscarConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonbuscarConsulta.setText("Buscar por CI");
        jButtonbuscarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbuscarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonbuscarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, 30));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Motivo de la consulta");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextAreaMotivo.setColumns(20);
        jTextAreaMotivo.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMotivo);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 910, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 1160, 120));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Diagnóstico");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextAreaDiagnostico.setColumns(20);
        jTextAreaDiagnostico.setLineWrap(true);
        jTextAreaDiagnostico.setRows(5);
        jTextAreaDiagnostico.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextAreaDiagnostico);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 910, 100));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 1140, 130));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOP1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonbuscarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbuscarConsultaActionPerformed
        if (jTextFieldBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "LLENAR CAMPO REQUERIDO", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            buscarConsulta(jTextFieldBuscar.getText());
        }
    }//GEN-LAST:event_jButtonbuscarConsultaActionPerformed

    private void TableConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableConsultasMouseClicked
        // TODO add your handling code here:

        int seleccionar = TableConsultas.getSelectedRow();
        int idConsulta = Integer.parseInt(model.getValueAt(seleccionar, 0).toString());
        Consulta con = conDB.traeConsulta(idConsulta);
        jTextAreaMotivo.setText(con.getMotivo());
        jTextAreaDiagnostico.setText(con.getDiagnostico());

    }//GEN-LAST:event_TableConsultasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmListaConsulta dialog = new frmListaConsulta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableConsultas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonbuscarConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDiagnostico;
    private javax.swing.JTextArea jTextAreaMotivo;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
