/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import Controlador.MascotaDB;
import Controlador.MascotaDB;
import Controlador.PersonaDB;
import Controlador.Validaciones;
import Modelo.Cuenta;
import Modelo.Mascota;
//import Modelo.Mascota;
import Modelo.Persona;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Personal
 */
public class frmMascota extends javax.swing.JDialog {
//    MascotaDB listaMascotas;
    /**
     * Creates new form frmMascota
     */
    PersonaDB persona = new PersonaDB();
    MascotaDB mascotaDB = new MascotaDB();
    Validaciones validar = new Validaciones();
    DefaultTableModel model;
    public frmMascota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMascotas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextColorPelaje = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextNombreMascota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jButtonModificar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxTamaño = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextRaza = new javax.swing.JTextField();
        jTextEdad = new javax.swing.JTextField();
        jTextEspecie = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextPresentarNombrePersona = new javax.swing.JTextField();
        jTextPresentarCedulaPersona = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextBuscarCedula = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR MASCOTA");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitulo.setText("REGISTRAR MASCOTA");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jTableMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE ", "ESPECIE", "RAZA", "SEXO", "DUEÑO", "CEDULA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMascotas.setGridColor(new java.awt.Color(153, 153, 255));
        jTableMascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMascotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMascotas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 1090, 246));

        jPanel1.setOpaque(false);
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel23.setText("Raza:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jTextColorPelaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextColorPelajeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextColorPelaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 155, 30));

        jLabel20.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel20.setText("Nombre:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 57, -1, -1));

        jTextNombreMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreMascotaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 270, 30));

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel10.setText("Sexo: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 50, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));
        jPanel1.add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 30));

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 90, 30));

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 100, 30));

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 90, 30));

        jLabel24.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel24.setText("Tamaño");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jComboBoxTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Mediano", "Pequeño" }));
        jPanel1.add(jComboBoxTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 100, 30));

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel11.setText("Especie: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, 30));

        jLabel12.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel12.setText("Edad:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 87, -1));

        jLabel25.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel25.setText("Color de Pelaje :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        jTextRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRazaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 155, 30));

        jTextEdad.setToolTipText("");
        jTextEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEdadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 155, 30));

        jTextEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEspecieActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 155, 30));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 1080, 200));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Cédula ");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 20));
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 148, -1, -1));

        jTextPresentarNombrePersona.setEditable(false);
        jPanel6.add(jTextPresentarNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 210, 30));

        jTextPresentarCedulaPersona.setEditable(false);
        jPanel6.add(jTextPresentarCedulaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 170, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Nombre");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 630, 70));

        jTextBuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextBuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 310, 30));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Número de Cédula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOP1.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel2");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextColorPelajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextColorPelajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextColorPelajeActionPerformed

    private void jTextNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreMascotaActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
            modificarMascota();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        registrarMascota();
        
    }//GEN-LAST:event_jButtonRegistrarActionPerformed
    
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        guardarModificacion();
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded

    }//GEN-LAST:event_jPanel1AncestorAdded

    private void jTextRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRazaActionPerformed

    private void jTextEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEdadActionPerformed

    private void jTextEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEspecieActionPerformed

    private void jTextBuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarCedulaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextBuscarCedulaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        buscarMascota();
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableMascotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMascotasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTableMascotas.getModel();
        String cedula = (String) modelo.getValueAt(jTableMascotas.getSelectedRow(), 5);
        String nombre = (String) modelo.getValueAt(jTableMascotas.getSelectedRow(), 0);
        Persona p = persona.traeClientesCedula(cedula);
        int id = p.getId_persona();
        Mascota m = mascotaDB.traerMascota(id, nombre);
        jTextNombreMascota.setText(m.getNombre());
        String s = m.getTamanio();
        int index;
        if(s.equals("Grande"))index=0;
        else if(s.equals("Mediano"))index=1;
        else index=2;
        jComboBoxTamaño.setSelectedIndex(index);
        jTextColorPelaje.setText(m.getColorPelaje());
        jTextEdad.setText(m.getEdad()+"");
        jTextRaza.setText(m.getRaza());
        String s1 = m.getSexo();
        int index1;
        if(s1.equals("Macho"))index1=0;
        else index1=1;
        jComboBoxSexo.setSelectedIndex(index1);
        jTextEspecie.setText(m.getEspecie());
        bloquearJtext();
    }//GEN-LAST:event_jTableMascotasMouseClicked
    
    public void modificarMascota(){
        if(jTableMascotas.getSelectedRow()>=0){
            bloquearJtext();
            DefaultTableModel modelo = (DefaultTableModel) jTableMascotas.getModel();
            String nombreM = (String) modelo.getValueAt(jTableMascotas.getSelectedRow(), 0);
            String cedula = jTextPresentarCedulaPersona.getText().trim();
            jTextEdad.enable();
            jTextEdad.updateUI();
            jComboBoxTamaño.enable();
            jComboBoxTamaño.updateUI();
            jButtonGuardar.setVisible(true);
            jButtonGuardar.enable();
            jButtonRegistrar.disable();
            jButtonRegistrar.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA");
        }
    }
    
    public void guardarModificacion(){
        DefaultTableModel modelo = (DefaultTableModel) jTableMascotas.getModel();
        String cedula = (String) modelo.getValueAt(jTableMascotas.getSelectedRow(), 5);
        String nombre = (String) modelo.getValueAt(jTableMascotas.getSelectedRow(), 0);
        Persona p = persona.traeClientesCedula(cedula);
        int id = p.getId_persona();
        Mascota m = mascotaDB.traerMascota(id, nombre);
        if(!jTextEdad.getText().equals("")){
            int edad = Integer.parseInt(jTextEdad.getText());
            m.setEdad(edad);
            m.setTamanio(jComboBoxTamaño.getSelectedItem().toString());
            mascotaDB.actualizarMascota(m);
            JOptionPane.showMessageDialog(null, "Mascota actualizada");
            limpiarJtext();
            jButtonGuardar.setVisible(false);
            jButtonRegistrar.enable();
            jButtonRegistrar.setVisible(true);
            llenarTabla(mascotaDB.listarMascotas());
            habititalJtext();
        }else{
            JOptionPane.showMessageDialog(null, "ingrece la edad");
        }
        
    }
    
    public void buscarMascota(){
        if(validar.esNumerico(jTextBuscarCedula.getText())){
            Persona p = persona.traeClientesCedula(jTextBuscarCedula.getText());
            if(p!=null){
                jTextPresentarNombrePersona.setText(p.getNombre()+" "+p.getApellido());
                jTextPresentarCedulaPersona.setText(p.getCedula());
                habititalJtext();
                int id = p.getId_persona();
                llenarTabla(mascotaDB.listarMascotasId(id));
                actualizarJtext();
                jTextBuscarCedula.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Persona no encontrada");
                jTextBuscarCedula.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
            jTextBuscarCedula.setText("");
            jTextPresentarNombrePersona.setText("");
            jTextPresentarCedulaPersona.setText("");
            limpiarTabla();
        }
    }
      
    public void registrarMascota(){
        System.out.println(jTextPresentarCedulaPersona.getText());
        if(!jTextPresentarCedulaPersona.getText().equals("")){//verifico si se ha buscado una persona
            if(!jTextNombreMascota.getText().equals("")&&!jTextEspecie.getText().equals("")&&!jTextRaza.getText().equals("")
               &&!jTextEdad.getText().equals("")&&!jTextColorPelaje.getText().equals("")){//verifico si se a llenado los campos
                if(validar.esNumerico(jTextEdad.getText())){//verifico si la edad se ha ingresado solo numeros
                    Persona p = persona.traeClientesCedula(jTextPresentarCedulaPersona.getText());
                    Mascota m = new Mascota();
                    m.setColorPelaje(jTextColorPelaje.getText().trim());
                    int edad = Integer.parseInt(jTextEdad.getText().trim());
                    m.setEdad(edad);
                    m.setEspecie(jTextEspecie.getText().trim());
                    m.setNombre(jTextNombreMascota.getText().trim());
                    m.setPersona(p);
                    m.setRaza(jTextRaza.getText().trim());
                    m.setSexo(jComboBoxSexo.getSelectedItem().toString());
                    m.setTamanio(jComboBoxTamaño.getSelectedItem().toString());
                    mascotaDB.nuevaMascota(m);
                    JOptionPane.showMessageDialog(null, "Mascota registrada");
                    limpiarJtext();
                    llenarTabla(mascotaDB.listarMascotas());
                    jTextPresentarCedulaPersona.setText("");
                    jTextPresentarNombrePersona.setText("");
                }else{
                    jTextEdad.setText("");
                    JOptionPane.showMessageDialog(null, "INGRESE LA EDAD EN NUMEROS");
                }
            }else{
                JOptionPane.showMessageDialog(null, "LLENE TODOS LOS CAMPOS");
            }
        }else{
            JOptionPane.showMessageDialog(null, "BUSQUE AL DUEÑO DE LA MASCOTA");
        }
    }
    public void inicializar(){
       jTextBuscarCedula.setToolTipText("Ingrese la cedula del dueño de la mascota. ");
       jButtonModificar.setToolTipText("Seleccione la mascota de la tabla antes de modificar.");
       jTextEdad.setToolTipText("Ingrese la edad en meses.");
       bloquearJtext();
       jButtonGuardar.setVisible(false);
       jButtonGuardar.disable();
       llenarTabla(mascotaDB.listarMascotas());
    }
    public void limpiarJtext(){
        jTextNombreMascota.setText("");
        jTextColorPelaje.setText("");
        jTextEdad.setText("");
        jTextRaza.setText("");
        jTextEspecie.setText("");
    } 
    public void bloquearJtext(){
        jTextNombreMascota.disable();
        jComboBoxTamaño.disable();
        jTextColorPelaje.disable();
        jTextEdad.disable(); 
        jTextRaza.disable();
        jComboBoxSexo.disable();
        jTextEspecie.disable();
    }
    public void habititalJtext(){
        jTextNombreMascota.enable();
        jComboBoxTamaño.enable();
        jTextColorPelaje.enable();
        jTextEdad.enable();
        jTextRaza.enable();
        jComboBoxSexo.enable();
        jTextEspecie.enable();
    }
    
    public void actualizarJtext(){
        jTextNombreMascota.updateUI();
        jComboBoxTamaño.updateUI();
        jTextColorPelaje.updateUI();
        jTextEdad.updateUI();
        jTextRaza.updateUI();
        jComboBoxSexo.updateUI();
        jTextEspecie.updateUI();
    }
    
    public void llenarTabla(List<Mascota> lista){
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NOMBRE","ESPECIE","RAZA","SEXO","DUEÑO","CEDULA"},lista.size());
        jTableMascotas.setModel(modelo);
        TableModel modeloDatos = jTableMascotas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            Mascota mascota= lista.get(i);
            modeloDatos.setValueAt(mascota.getNombre().toUpperCase(), i, 0);
            modeloDatos.setValueAt(mascota.getEspecie().toUpperCase(), i, 1);
            modeloDatos.setValueAt(mascota.getRaza().toUpperCase(), i, 2);
            modeloDatos.setValueAt(mascota.getSexo().toUpperCase(), i, 3);
            String dueño = mascota.getPersona().getNombre().toUpperCase()+" "+mascota.getPersona().getApellido().toUpperCase();
            modeloDatos.setValueAt(dueño, i, 4);
            modeloDatos.setValueAt(mascota.getPersona().getCedula().toUpperCase(), i, 5);
        }
    }
    private void limpiarTabla(){
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NOMBRE","ESPECIE","RAZA","SEXO","DUEÑO","CEDULA"},0);
        jTableMascotas.setModel(modelo);
        jTableMascotas.updateUI();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMascota dialog = new frmMascota(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTamaño;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMascotas;
    private javax.swing.JTextField jTextBuscarCedula;
    private javax.swing.JTextField jTextColorPelaje;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextEspecie;
    private javax.swing.JTextField jTextNombreMascota;
    private javax.swing.JTextField jTextPresentarCedulaPersona;
    private javax.swing.JTextField jTextPresentarNombrePersona;
    private javax.swing.JTextField jTextRaza;
    // End of variables declaration//GEN-END:variables
}
