/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import Modelo.Hospitalizacion;
import Modelo.Cuenta;
import Modelo.Hospitalizacion;

/**
 *
 * @author Personal
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    int tipo = 0;
    Cuenta cuenta = new Cuenta();

    public frmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public frmPrincipal(int tip) {
        initComponents();
        tipo = tip;

        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Menu Principal");
        menus();
    }

    private void menus() {
        if (tipo == 2) { //administrador

            jMenuAdministrarCuentas.setEnabled(true);
            jCheckListaCuentas.setEnabled(true);
            jCheckRegistrarCuenta.setEnabled(true);
            jMenuBar1.setEnabled(true);
            jMenuServicios.setEnabled(true);
            jCheckRegistrarServicios.setEnabled(true);
          jRegistrarReceta.setEnabled(true);
            jCheckListaHospita.setEnabled(true);
            jCheckListaConsultas.setEnabled(true);
            jMenuClientes.setEnabled(true);
            jCheckRegistrarCliente.setEnabled(true);
            jCheckListaClientes.setEnabled(true);
            jCheckMascotas.setEnabled(true);
            jMenuFacturas.setEnabled(true);
            jCheckListaFacturas.setEnabled(true);
            jMenuRecetas.setEnabled(true);
            jMenuListaPrincipal.setEnabled(true);
            jMenuSalir.setEnabled(true);
            jCheckCerrarSesion.setEnabled(true);    
        }
                if (tipo == 3) { //secretaria

            jMenuAdministrarCuentas.setEnabled(false);
            jCheckListaCuentas.setEnabled(false);
            jCheckRegistrarCuenta.setEnabled(false);
            jMenuBar1.setEnabled(true);
            jMenuServicios.setEnabled(true);
            jCheckRegistrarServicios.setEnabled(false);
          jRegistrarReceta.setEnabled(false);
            jCheckListaHospita.setEnabled(false);
            jCheckListaConsultas.setEnabled(false);
            jMenuClientes.setEnabled(true);
            jCheckRegistrarCliente.setEnabled(true);
            jCheckListaClientes.setEnabled(true);
            jCheckMascotas.setEnabled(true);
            jMenuFacturas.setEnabled(true);
            jCheckListaFacturas.setEnabled(true);
            jMenuRecetas.setEnabled(false);
            jMenuListaPrincipal.setEnabled(false);
            jMenuSalir.setEnabled(true);
            jCheckCerrarSesion.setEnabled(true);    
            jMenuServicios.setEnabled(false);
            btnConsultas.setEnabled(false);
            btnHospitalizacion.setEnabled(false);
        }
                        if (tipo == 4) { //veterinario

            jMenuAdministrarCuentas.setEnabled(false);
            jCheckListaCuentas.setEnabled(false);
            jCheckRegistrarCuenta.setEnabled(false);
            jMenuBar1.setEnabled(true);
            jMenuServicios.setEnabled(false);
            jCheckRegistrarServicios.setEnabled(false);
    
           jRegistrarReceta.setEnabled(true);
            jCheckListaHospita.setEnabled(true);
            jCheckListaConsultas.setEnabled(true);
            jMenuClientes.setEnabled(false);
            jCheckRegistrarCliente.setEnabled(false);
            jCheckListaClientes.setEnabled(false);
            jCheckMascotas.setEnabled(false);
            jMenuFacturas.setEnabled(false);
            jCheckListaFacturas.setEnabled(false);
            jMenuRecetas.setEnabled(true);
            jMenuListaPrincipal.setEnabled(true);
            jMenuSalir.setEnabled(true);
            jCheckCerrarSesion.setEnabled(true);    
            jMenuServicios.setEnabled(true);
            btnFacturacion.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHospitalizacion = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministrarCuentas = new javax.swing.JMenu();
        jCheckListaCuentas = new javax.swing.JCheckBoxMenuItem();
        jCheckRegistrarCuenta = new javax.swing.JCheckBoxMenuItem();
        jMenuServicios = new javax.swing.JMenu();
        jCheckRegistrarServicios = new javax.swing.JCheckBoxMenuItem();
        jCheckListaHospita = new javax.swing.JCheckBoxMenuItem();
        jCheckListaConsultas = new javax.swing.JCheckBoxMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jCheckRegistrarCliente = new javax.swing.JCheckBoxMenuItem();
        jCheckListaClientes = new javax.swing.JCheckBoxMenuItem();
        jCheckMascotas = new javax.swing.JCheckBoxMenuItem();
        jMenuFacturas = new javax.swing.JMenu();
        jCheckListaFacturas = new javax.swing.JCheckBoxMenuItem();
        jMenuRecetas = new javax.swing.JMenu();
        jMenuListaPrincipal = new javax.swing.JMenuItem();
        jRegistrarReceta = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jCheckCerrarSesion = new javax.swing.JCheckBoxMenuItem();
        jMenuSalir1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHospitalizacion.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        btnHospitalizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hospitalizacion.jpg"))); // NOI18N
        btnHospitalizacion.setText("HOSPITALIZACIÓN");
        btnHospitalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalizacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnHospitalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 430, 240));

        btnConsultas.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta.jpg"))); // NOI18N
        btnConsultas.setText("CONSULTA");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 430, 240));

        btnFacturacion.setFont(new java.awt.Font("Constantia", 1, 24)); // NOI18N
        btnFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Facturacion.jpg"))); // NOI18N
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 660, 270));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOP1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuAdministrarCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrarcuenta.png"))); // NOI18N
        jMenuAdministrarCuentas.setText("Administrar Cuentas ");

        jCheckListaCuentas.setSelected(true);
        jCheckListaCuentas.setText("Lista de Cuentas");
        jCheckListaCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listacuenta.png"))); // NOI18N
        jCheckListaCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckListaCuentasActionPerformed(evt);
            }
        });
        jMenuAdministrarCuentas.add(jCheckListaCuentas);

        jCheckRegistrarCuenta.setSelected(true);
        jCheckRegistrarCuenta.setText("Registrar Cuenta");
        jCheckRegistrarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuenta.png"))); // NOI18N
        jCheckRegistrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRegistrarCuentaActionPerformed(evt);
            }
        });
        jMenuAdministrarCuentas.add(jCheckRegistrarCuenta);

        jMenuBar1.add(jMenuAdministrarCuentas);

        jMenuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrarservicios.png"))); // NOI18N
        jMenuServicios.setText(" Servicios");

        jCheckRegistrarServicios.setSelected(true);
        jCheckRegistrarServicios.setText("Registrar Servicios");
        jCheckRegistrarServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarservicio.png"))); // NOI18N
        jCheckRegistrarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRegistrarServiciosActionPerformed(evt);
            }
        });
        jMenuServicios.add(jCheckRegistrarServicios);

        jCheckListaHospita.setSelected(true);
        jCheckListaHospita.setText("Lista de Hospitalización");
        jCheckListaHospita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listahospitalizacion.png"))); // NOI18N
        jCheckListaHospita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckListaHospitaActionPerformed(evt);
            }
        });
        jMenuServicios.add(jCheckListaHospita);

        jCheckListaConsultas.setSelected(true);
        jCheckListaConsultas.setText("Lista de Consulta");
        jCheckListaConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listaconsulta.png"))); // NOI18N
        jCheckListaConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckListaConsultasActionPerformed(evt);
            }
        });
        jMenuServicios.add(jCheckListaConsultas);

        jMenuBar1.add(jMenuServicios);

        jMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listacuenta.png"))); // NOI18N
        jMenuClientes.setText(" Clientes");

        jCheckRegistrarCliente.setSelected(true);
        jCheckRegistrarCliente.setText("Registrar Cliente");
        jCheckRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrarcliente.png"))); // NOI18N
        jCheckRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRegistrarClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jCheckRegistrarCliente);

        jCheckListaClientes.setSelected(true);
        jCheckListaClientes.setText("Lista de Clientes");
        jCheckListaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listaclientes.png"))); // NOI18N
        jCheckListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckListaClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(jCheckListaClientes);

        jCheckMascotas.setSelected(true);
        jCheckMascotas.setText("Mascotas");
        jCheckMascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listaclientes.png"))); // NOI18N
        jCheckMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMascotasActionPerformed(evt);
            }
        });
        jMenuClientes.add(jCheckMascotas);

        jMenuBar1.add(jMenuClientes);

        jMenuFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        jMenuFacturas.setText("Facturas");

        jCheckListaFacturas.setSelected(true);
        jCheckListaFacturas.setText("Lista de Facturas");
        jCheckListaFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listafactura.png"))); // NOI18N
        jCheckListaFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckListaFacturasActionPerformed(evt);
            }
        });
        jMenuFacturas.add(jCheckListaFacturas);

        jMenuBar1.add(jMenuFacturas);

        jMenuRecetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/receta1.png"))); // NOI18N
        jMenuRecetas.setText("Recetas");

        jMenuListaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/receta.png"))); // NOI18N
        jMenuListaPrincipal.setText("Lista de recetas");
        jMenuListaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaPrincipalActionPerformed(evt);
            }
        });
        jMenuRecetas.add(jMenuListaPrincipal);

        jRegistrarReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/receta.png"))); // NOI18N
        jRegistrarReceta.setText("Registrar receta");
        jRegistrarReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistrarRecetaActionPerformed(evt);
            }
        });
        jMenuRecetas.add(jRegistrarReceta);

        jMenuBar1.add(jMenuRecetas);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/x.png"))); // NOI18N
        jMenuSalir.setText("Salir");

        jCheckCerrarSesion.setSelected(true);
        jCheckCerrarSesion.setText("Cerrar Sesión");
        jCheckCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrasesion.png"))); // NOI18N
        jCheckCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCerrarSesionActionPerformed(evt);
            }
        });
        jMenuSalir.add(jCheckCerrarSesion);

        jMenuSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N
        jMenuSalir1.setText("Salir de la Aplicacion");
        jMenuSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalir1ActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuSalir1);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckRegistrarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRegistrarServiciosActionPerformed
      frmServicio servicio = new frmServicio(this, rootPaneCheckingEnabled);
      servicio.setTitle("Registrar Servicio");
      servicio.setVisible(true);
    }//GEN-LAST:event_jCheckRegistrarServiciosActionPerformed

    private void jCheckRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRegistrarClienteActionPerformed
        // TODO add your handling code here:
        frmPersona rp = new frmPersona(this, false, true, false, "");
        rp.setVisible(true);
    }//GEN-LAST:event_jCheckRegistrarClienteActionPerformed

    private void jCheckListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckListaClientesActionPerformed
        // TODO add your handling code here:
        frmListaPersonas lp = new frmListaPersonas(this, false, true);
        lp.setVisible(true);
    }//GEN-LAST:event_jCheckListaClientesActionPerformed

    private void jCheckCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCerrarSesionActionPerformed
      frmInicioSesion ini= new frmInicioSesion(this, rootPaneCheckingEnabled);
     dispose();
      ini.setVisible(true);// TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckCerrarSesionActionPerformed

    private void jCheckListaHospitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckListaHospitaActionPerformed
        // TODO add your handling code here:
        frmListaHospitalización flh = new frmListaHospitalización(this, false);
        flh.setVisible(true);
    }//GEN-LAST:event_jCheckListaHospitaActionPerformed

    private void jCheckListaConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckListaConsultasActionPerformed
        // TODO add your handling code here:

        frmListaConsulta fc = new frmListaConsulta(this, false);
        fc.setVisible(true);

    }//GEN-LAST:event_jCheckListaConsultasActionPerformed

    private void jCheckListaCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckListaCuentasActionPerformed
        // TODO add your handling code here:
        frmListaPersonas lp = new frmListaPersonas(this, false, false);
        lp.setVisible(true);
    }//GEN-LAST:event_jCheckListaCuentasActionPerformed

    private void jCheckListaFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckListaFacturasActionPerformed
       frmListaFactura lista = new frmListaFactura(this, true);
       lista.setLocationRelativeTo(null);
       lista.setVisible(true);
    }//GEN-LAST:event_jCheckListaFacturasActionPerformed

    private void btnHospitalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalizacionActionPerformed
        // TODO add your handling code here:
        frmHospitalizacion fh = new frmHospitalizacion(this, true, false, new Hospitalizacion());
        fh.setVisible(true);
    }//GEN-LAST:event_btnHospitalizacionActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
       frmFactura factura = new frmFactura(this,true);
       factura.setLocationRelativeTo(null);
       factura.setVisible(true);
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void jCheckRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRegistrarCuentaActionPerformed
        // TODO add your handling code here:
        frmPersona rp = new frmPersona(this, false, false, false, "");
        rp.setVisible(true);
    }//GEN-LAST:event_jCheckRegistrarCuentaActionPerformed

    private void jCheckMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMascotasActionPerformed
        // TODO add your handling code here:
        frmMascota m = new frmMascota(this, false);
        m.setVisible(true);
    }//GEN-LAST:event_jCheckMascotasActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
        frmConsulta vc = new frmConsulta(this, true);
        vc.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void jMenuListaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaPrincipalActionPerformed
       frmListaRecetas rec = new frmListaRecetas();
       rec.setVisible(true);

    }//GEN-LAST:event_jMenuListaPrincipalActionPerformed

    private void jMenuSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSalir1ActionPerformed

    private void jRegistrarRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistrarRecetaActionPerformed
       frmReceta fr = new frmReceta();
      fr.setVisible(true);
    }//GEN-LAST:event_jRegistrarRecetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnHospitalizacion;
    private javax.swing.JCheckBoxMenuItem jCheckCerrarSesion;
    private javax.swing.JCheckBoxMenuItem jCheckListaClientes;
    private javax.swing.JCheckBoxMenuItem jCheckListaConsultas;
    private javax.swing.JCheckBoxMenuItem jCheckListaCuentas;
    private javax.swing.JCheckBoxMenuItem jCheckListaFacturas;
    private javax.swing.JCheckBoxMenuItem jCheckListaHospita;
    private javax.swing.JCheckBoxMenuItem jCheckMascotas;
    private javax.swing.JCheckBoxMenuItem jCheckRegistrarCliente;
    private javax.swing.JCheckBoxMenuItem jCheckRegistrarCuenta;
    private javax.swing.JCheckBoxMenuItem jCheckRegistrarServicios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAdministrarCuentas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuFacturas;
    private javax.swing.JMenuItem jMenuListaPrincipal;
    private javax.swing.JMenu jMenuRecetas;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenuItem jMenuSalir1;
    private javax.swing.JMenu jMenuServicios;
    private javax.swing.JMenuItem jRegistrarReceta;
    // End of variables declaration//GEN-END:variables

    private frmListaRecetas frmListaRecetas(frmPrincipal aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
