/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import Controlador.RecetaDB;
import Controlador.RecetaDB;
import Controlador.Validaciones;
import Modelo.Consulta;
import Modelo.Receta;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class frmReceta extends javax.swing.JFrame {

    /**
     * Creates new form frmReceta
     */
    
    RecetaDB recetaDB = new RecetaDB();
    Consulta mas = null;
    
   DefaultTableModel model1 = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    DefaultTableModel modelConsulta;
    Validaciones val = new Validaciones();
    public frmReceta() {
        initComponents();  
//        txtNro.setText(val.ObtenerCodString(obtenerCodigoReceta()));
        inicio();
    }
        private void inicio() {
        //TableModelConsulta();      
//        btnNuevo.setEnabled(true);
        btnImprimir.setText("Imprimir");       
        btnCancelar.setEnabled(true);

//        Activa_DesactivaCampos(false);
//        TablaCita.setEnabled(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCi = new javax.swing.JTextField();
        txtMascota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAindicaciones = new javax.swing.JTextArea();
        txtNro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAmedicamentos = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("RECETA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CI:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mascota:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nro. de Receta");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiActionPerformed(evt);
            }
        });
        getContentPane().add(txtCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 200, 20));

        txtMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMascotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, 20));

        txtAindicaciones.setColumns(20);
        txtAindicaciones.setLineWrap(true);
        txtAindicaciones.setRows(5);
        txtAindicaciones.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAindicaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 290, 240));

        txtNro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 20));

        txtAmedicamentos.setColumns(20);
        txtAmedicamentos.setLineWrap(true);
        txtAmedicamentos.setRows(5);
        txtAmedicamentos.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAmedicamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 290, 240));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Indicaciones");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Medicamentos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 110, 30));

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cliente:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, 20));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 110, 30));
        getContentPane().add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOP1.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void Bloquear(boolean flag) {

        if (flag == true) {
            btnImprimir.setEnabled(true);
            btnCancelar.setEnabled(false);
            txtAindicaciones.setEnabled(false);
            txtAmedicamentos.setEnabled(false);
        }
    }
//   private void guardar() {
//        Receta rec = null;
//
//        if (btnImprimir.getText().equals("Imprimir")) {
//            
////            rec = recetaDB.traeRecetaID(txtId.getText());
////            txtCedula.setText(String.valueOf(cedula));
////          txtId.setText(String.valueOf(rec.getId_serv()));  
////            txtId.getText(
//            if (rec == null) {
// 
//                if (ValidarCampos() == true) {
//                    rec = new Receta();                 
//                    rec.setConsulta(mas);
//                    rec.setNum_receta(txtNro.getText());
//                    rec.setFecha_receta(jDate.getCalendar());
//                    rec.setIndicac_receta(txtAindicaciones.getText());
//                    rec.setMedicam_receta(txtAmedicamentos.getText());                  
//                    rec.setEstado("A");                 
//                    recetaDB.nuevaReceta(rec);
//                    inicio();
//                } else {
//                    JOptionPane.showMessageDialog(null, "LLENAR CAMPOS REQUERIDOS", "Mensaje", JOptionPane.WARNING_MESSAGE);
////                    activa_Desac_Panel(false);
//                    inicio();
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "EL NOMBRE DE LA ESPECIALIDAD YA EXISTE EN EL SISTEMA", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
//            }
//
//        } 
//        inicio();
//
//    }
       private void guardar1() {
         Receta rec = null;

        if ( jDate.getCalendar() == null) {
            JOptionPane.showMessageDialog(null, "LLENAR CAMPOS REQUERIDOS", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
         
            jDate.setCalendar(null);

        } else {
            if (btnImprimir.getText().equals("Imprimir")) {        
                    rec = new Receta();                 
                    rec.setConsulta(mas);
                    rec.setNum_receta(txtNro.getText());
                    rec.setFecha_receta(jDate.getCalendar());
                    rec.setIndicac_receta(txtAindicaciones.getText());
                    rec.setMedicam_receta(txtAmedicamentos.getText());                  
                    rec.setEstado("A");                 
                    recetaDB.nuevaReceta(rec);    
                JOptionPane.showMessageDialog(null, "RECETA REGISTRADA ", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } 
            inicio();
        }
    }
   
    private boolean ValidarCampos() {
        boolean lleno = true;
        if (txtAindicaciones.getText().equals("") || txtAmedicamentos.getText().equals("")) {
            lleno = false;
        } else {
            lleno = true;
        }
        return lleno;
    }
//    
//    int num_resp = 0;
//         public int obtenerCodigoReceta() {
//        num_resp = 0;
//        List<Receta> lista = null;
//        lista = recetaDB.cargarCodigoReceta(lista);
//        for (Iterator<Receta> it = lista.iterator(); it.hasNext();) {
//            Receta rec = it.next();
//            num_resp = Integer.parseInt(rec.getNum_receta()) + 1;
//        }
//        if (num_resp == 0) {
//            num_resp = 1;
//        }
//        return num_resp;
//    }
         
         
    
    private void txtCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiActionPerformed

    private void txtMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMascotaActionPerformed

    private void txtNroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
guardar1();    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReceta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAindicaciones;
    private javax.swing.JTextArea txtAmedicamentos;
    public static javax.swing.JTextField txtCi;
    public static javax.swing.JTextField txtCliente;
    public static javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtNro;
    // End of variables declaration//GEN-END:variables
}
